replicaCount: 1

image:
  repository: pavlospt/go-app
  pullPolicy: Always
  tag: "latest"

labels: "go-app"
selectorLabels: "go-app"

service:
  name: "go-app-svc"
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

health:
  path: /
  port: 8080
