name: Main - Publish Docker image 

on:
  push:
    branches: [main]
    paths:
      - 'app/**.go'

jobs:
  push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Extrach branch name
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: pavlospt
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        run: make build_docker_image
      - uses: sigstore/cosign-installer@main
      - name: Sign Docker image
        run: make sign_docker_image
        env:
          # This is needed in order to use Sigstore Fulcio instance
          COSIGN_EXPERIMENTAL: "true"
