name: PR - Publish Docker image 

on:
  pull_request:
    # paths:
    #   - 'app/**.go'

jobs:
  push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Extrach branch name
        # Docker tags can not contain slashes so we need to replace them with dash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          working-directory: app
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: pavlospt
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: "pavlospt/go-app:${{ env.BRANCH_NAME }}"
      - uses: sigstore/cosign-installer@main
      - name: Sign Docker image
        run: >
          cosign sign 
          -a "repo=${{ github.repository }}"
          -a "workflow=${{ github.workflow }}"
          -a "ref=${{ github.sha }}"
          pavlospt/go-app:${{ env.BRANCH_NAME }}
        env:
          # This is needed in order to use Sigstore Fulcio instance
          COSIGN_EXPERIMENTAL: "true"
