name: Tag - Publish Docker image & deploy

on:
  push:
    tags:
      - '*'

jobs:
  push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Extract tag name
        run: echo "TAG_NAME=$(echo ${GITHUB_REF#refs/tags/})" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: pavlospt
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: "pavlospt/go-app:${{ env.TAG_NAME }}"
      - uses: azure/setup-helm@v1
      - name: Package Helm charts
        run: >
          helm package 
          go-app-charts 
          -d go-app-charts/charts 
          --app-version ${{ env.TAG_NAME }} 
          --version ${{ env.TAG_NAME }}
      # The following steps are needed in order to get a kubeconfig entry with our credentials
      - name: Authenticate with Google project
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/761151480908/locations/global/workloadIdentityPools/github-actions-identity-pool/providers/github-actions-idp'
          service_account: 'gha-sa@go-cluster-gke.iam.gserviceaccount.com'
      - name: Export KUBECONFIG credentials
        uses: 'google-github-actions/get-gke-credentials@v0'
        with:
          cluster_name: 'go-cluster-gke-gke'
          location: 'europe-west1'
      - name: Install Helm chart
        run: >
          helm upgrade
          --install
          --force
          --create-namespace
          -n devops-challenge
          --set image.tag=${{ env.TAG_NAME }}
          --kubeconfig ${{ env.KUBECONFIG }}
          go-app
          ./go-app-charts/charts/go-app-${{ env.TAG_NAME }}.tgz
  
  package_helm:
    name: Prepare application Helm package
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Extract tag name
        run: echo "TAG_NAME=$(echo ${GITHUB_REF#refs/tags/})" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2
      - uses: azure/setup-helm@v1
      - name: Package Helm charts
        run: >
          helm package 
          go-app-charts 
          -d go-app-charts/charts 
          --app-version ${{ env.TAG_NAME }} 
          --version ${{ env.TAG_NAME }}
      - name: Create a Github release with Helm package
        uses: softprops/action-gh-release@v1
        with:
          files: go-app-charts/charts/go-app-chart-${{ env.TAG_NAME }}.tgz
